### PR TITLE
Add new env vble for v8config file

### PR DESCRIPTION
**Pull request by igayoso**
In UNIX systems is a problem modify HOME env variable so is a good idea have the option to set new config path to v8 file. With the PR you will can setup a environment variable with the path without modify HOME environment variable

### CODE REVIEW

**Comment by tkellen** [comment]
What is the situation where you don't have write access to your own home directory?

**Comment by igayoso** [comment]
We're using in travis-ci and we run behat tests as www-user from travis home user directory so we don't have permission and we have to make a horrible workaround to fix issue.

**Comment by tkellen** [comment]
I'm sorry you're having to deal with this. I believe the correct solution for this is what is outlined in #29, not adding another environment flag.

**Comment by igayoso** [comment]
Is a good solution but IMHO is not the same issue. BTW, how could be possible to get tmp env vble instead of home vble? Is only for Windows? Adding this new env vble solve these problems...

Feel you free to close my PR, thanks!

**Comment by phated** [comment]
I agree with @tkellen - we should just better handle scenarios where we can't write (by not writing and not crashing).

**Pull request closed without merging**
